apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.httprouteName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sglang-1p1d.labels" . | nindent 4 }}
    app.kubernetes.io/component: router
spec:
  hostnames:
    - {{ .Values.gateway.hostname }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.parentGateway }}
      namespace: {{ .Values.gateway.parentNamespace }}
      sectionName: http
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.parentGateway }}
      namespace: {{ .Values.gateway.parentNamespace }}
      sectionName: https-{{ .Values.gateway.httprouteName }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "sglang-1p1d.name" . }}-router
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.router.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
