apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: sglang-glm52-2tp8
    meta.helm.sh/release-namespace: kube-system
    service.cloud.tencent.com/sync-begin-time: "2026-07-16T16:25:45+08:00"
    service.cloud.tencent.com/sync-end-time: "2026-07-16T16:25:45+08:00"
  creationTimestamp: "2026-07-16T08:25:44Z"
  labels:
    accelerator: amd-gpu
    app: sglang-router
    app.kubernetes.io/instance: sglang-glm52-2tp8
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sglang-glm52-308x
    helm.sh/chart: sglang-glm52-308x-0.1.0
  name: sglang-glm52-2tp8-router
  namespace: kube-system
  resourceVersion: "270424242"
  uid: e53f6fda-ce17-47a2-b5c7-b3a6f480622e
spec:
  clusterIP: 9.165.46.118
  clusterIPs:
  - 9.165.46.118
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 30001
    protocol: TCP
    targetPort: http
  selector:
    app: sglang-router
  sessionAffinity: None
  type: ClusterIP
status:
  conditions:
  - lastTransitionTime: "2026-07-16T08:25:45Z"
    message: ""
    reason: Success
    status: "True"
    type: Ready
  loadBalancer: {}
